// packages/adapters/svelte/src/Dropdown.svelte
<script lang="ts" context="module">
  export const __ffClasses_Dropdown = [
    'ff-dropdown',
    'ff-dropdown-trigger',
    'ff-dropdown-menu',
    'ff-dropdown-menu-right',
    'ff-dropdown-item'
  ];
</script>

<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { useFinggu } from './context';

  export let align: 'left' | 'right' = 'left';

  const finggu = useFinggu();
  let isOpen = false;
  let container: HTMLElement;

  function toggle() { isOpen = !isOpen; }
  function close() { isOpen = false; }

  function handleClickOutside(event: MouseEvent) {
    if (container && !container.contains(event.target as Node)) {
      close();
    }
  }

  onMount(() => {
    if (typeof document !== 'undefined') {
      document.addEventListener('mousedown', handleClickOutside);
    }
  });

  onDestroy(() => {
    if (typeof document !== 'undefined') {
      document.removeEventListener('mousedown', handleClickOutside);
    }
  });

  $: ffContainerClasses = $finggu.resolveAll(['ff-dropdown']);
  $: ffTriggerClasses = $finggu.resolveAll(['ff-dropdown-trigger']);
  $: ffMenuClasses = $finggu.resolveAll([
    'ff-dropdown-menu',
    align === 'right' && 'ff-dropdown-menu-right'
  ]);
</script>

<div class={ffContainerClasses} bind:this={container}>
  <button
    type="button"
    class={ffTriggerClasses}
    on:click={toggle}
    aria-haspopup="true"
    aria-expanded={isOpen}
  >
    <slot name="trigger" />
  </button>

  <div
    class={ffMenuClasses}
    data-ff-state={isOpen ? 'open' : 'closed'}
    role="menu"
    aria-hidden={!isOpen}
  >
    <slot />
  </div>
</div>

// packages/adapters/vue/src/Dropdown.vue
<template>
  <div :class="ffContainerClasses" ref="containerRef">
    <button
      type="button"
      :class="ffTriggerClasses"
      @click="toggle"
      aria-haspopup="true"
      :aria-expanded="isOpen"
    >
      <slot name="trigger" />
    </button>
    <div
      :class="ffMenuClasses"
      :data-ff-state="isOpen ? 'open' : 'closed'"
      role="menu"
      :aria-hidden="!isOpen"
    >
      <slot />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted, onUnmounted, computed, PropType } from 'vue';
import { useFinggu } from './composable';

export const __ffClasses_Dropdown = [
  'ff-dropdown',
  'ff-dropdown-trigger',
  'ff-dropdown-menu',
  'ff-dropdown-menu-right',
  'ff-dropdown-item'
];

export default defineComponent({
  name: 'FingguDropdown',
  props: {
    align: {
      type: String as PropType<'left' | 'right'>,
      default: 'left'
    }
  },
  setup(props) {
    const { resolveAll } = useFinggu();
    const isOpen = ref(false);
    const containerRef = ref<HTMLElement | null>(null);

    const toggle = () => { isOpen.value = !isOpen.value; };
    const close = () => { isOpen.value = false; };

    const handleClickOutside = (event: MouseEvent) => {
      if (containerRef.value && !containerRef.value.contains(event.target as Node)) {
        close();
      }
    };

    onMounted(() => {
      document.addEventListener('mousedown', handleClickOutside);
    });

    onUnmounted(() => {
      document.removeEventListener('mousedown', handleClickOutside);
    });

    const ffContainerClasses = computed(() => resolveAll(['ff-dropdown']));
    const ffTriggerClasses = computed(() => resolveAll(['ff-dropdown-trigger']));
    const ffMenuClasses = computed(() => resolveAll([
      'ff-dropdown-menu',
      props.align === 'right' && 'ff-dropdown-menu-right'
    ]));

    return { 
      isOpen, 
      containerRef, 
      toggle, 
      ffContainerClasses, 
      ffTriggerClasses, 
      ffMenuClasses 
    };
  }
});

// DropdownItem as a simple functional-like component
export const DropdownItem = defineComponent({
  name: 'FingguDropdownItem',
  setup(_, { slots, attrs }) {
    const { resolveAll } = useFinggu();
    const ffClasses = computed(() => resolveAll(['ff-dropdown-item', attrs.class as string]));
    return () => h('div', { ...attrs, class: ffClasses.value }, slots.default?.());
  }
});
import { h } from 'vue';
</script>
