// packages/adapters/react/src/input.tsx
import React from 'react';
import { useFinggu } from './provider';

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
    error?: boolean;
}

export const __ffClasses_Input = [
    'ff-input',
    'ff-input-error'
];

export const Input: React.FC<InputProps> = ({ error, className, ...props }) => {
    const { resolveAll } = useFinggu();

    const ffClasses = resolveAll([
        'ff-input',
        error && 'ff-input-error',
        className
    ]);

    return <input className={ffClasses} {...props} />;
};

// packages/adapters/vue/src/Input.vue
<template>
  <input :class="ffClasses" v-bind="$attrs" />
</template>

<script lang="ts">
import { defineComponent, computed } from 'vue';
import { useFinggu } from './composable';

export const __ffClasses_Input = [
  'ff-input',
  'ff-input-error'
];

export default defineComponent({
  name: 'FingguInput',
  inheritAttrs: false,
  props: {
    error: {
      type: Boolean,
      default: false
    }
  },
  setup(props) {
    const { resolveAll } = useFinggu();
    const ffClasses = computed(() => resolveAll([
      'ff-input',
      props.error && 'ff-input-error'
    ]));
    return { ffClasses };
  }
});
</script>
