// packages/adapters/react/src/dropdown.tsx
import React, { useState, useRef, useEffect } from 'react';
import { useFinggu } from './provider';

export interface DropdownProps {
    trigger: React.ReactNode;
    children: React.ReactNode;
    align?: 'left' | 'right';
}

export const __ffClasses_Dropdown = [
    'ff-dropdown',
    'ff-dropdown-trigger',
    'ff-dropdown-menu',
    'ff-dropdown-menu-right',
    'ff-dropdown-item'
];

export const Dropdown: React.FC<DropdownProps> = ({ trigger, children, align = 'left' }) => {
    const [isOpen, setIsOpen] = useState(false);
    const containerRef = useRef<HTMLDivElement>(null);
    const { resolveAll } = useFinggu();

    useEffect(() => {
        const handleClickOutside = (event: MouseEvent) => {
            if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
                setIsOpen(false);
            }
        };
        document.addEventListener('mousedown', handleClickOutside);
        return () => document.removeEventListener('mousedown', handleClickOutside);
    }, []);

    return (
        <div className={resolveAll(['ff-dropdown'])} ref={containerRef}>
            <button
                type="button"
                className={resolveAll(['ff-dropdown-trigger'])}
                onClick={() => setIsOpen(!isOpen)}
                aria-haspopup="true"
                aria-expanded={isOpen}
            >
                {trigger}
            </button>
            <div
                className={resolveAll([
                    'ff-dropdown-menu',
                    align === 'right' && 'ff-dropdown-menu-right'
                ])}
                data-ff-state={isOpen ? 'open' : 'closed'}
                role="menu"
                aria-hidden={!isOpen}
            >
                {children}
            </div>
        </div>
    );
};

export const DropdownItem: React.FC<React.HTMLAttributes<HTMLDivElement>> = ({ className, children, ...props }) => {
    const { resolveAll } = useFinggu();
    return <div className={resolveAll(['ff-dropdown-item', className])} {...props}>{children}</div>;
};

// packages/adapters/svelte/src/Dropdown.svelte
<script lang="ts" context="module">
  export const __ffClasses_Dropdown = [
    'ff-dropdown',
    'ff-dropdown-trigger',
    'ff-dropdown-menu',
    'ff-dropdown-menu-right',
    'ff-dropdown-item'
  ];
</script>

<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { useFinggu } from './context';

  export let align: 'left' | 'right' = 'left';

  const finggu = useFinggu();
  let isOpen = false;
  let container: HTMLElement;

  function toggle() { isOpen = !isOpen; }
  function close() { isOpen = false; }

  function handleClickOutside(event: MouseEvent) {
    if (container && !container.contains(event.target as Node)) {
      close();
    }
  }

  onMount(() => {
    if (typeof document !== 'undefined') {
      document.addEventListener('mousedown', handleClickOutside);
    }
  });

  onDestroy(() => {
    if (typeof document !== 'undefined') {
      document.removeEventListener('mousedown', handleClickOutside);
    }
  });

  $: ffContainerClasses = $finggu.resolveAll(['ff-dropdown']);
  $: ffTriggerClasses = $finggu.resolveAll(['ff-dropdown-trigger']);
  $: ffMenuClasses = $finggu.resolveAll([
    'ff-dropdown-menu',
    align === 'right' && 'ff-dropdown-menu-right'
  ]);
</script>

<div class={ffContainerClasses} bind:this={container}>
  <button
    type="button"
    class={ffTriggerClasses}
    on:click={toggle}
    aria-haspopup="true"
    aria-expanded={isOpen}
  >
    <slot name="trigger" />
  </button>

  <div
    class={ffMenuClasses}
    data-ff-state={isOpen ? 'open' : 'closed'}
    role="menu"
    aria-hidden={!isOpen}
  >
    <slot />
  </div>
</div>
