// packages/adapters/react/src/input.tsx
import React from 'react';
import { useFinggu } from './provider';

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
    error?: boolean;
}

export const __ffClasses_Input = [
    'ff-input',
    'ff-input-error'
];

export const Input: React.FC<InputProps> = ({ error, className, ...props }) => {
    const { resolveAll } = useFinggu();

    const ffClasses = resolveAll([
        'ff-input',
        error && 'ff-input-error',
        className
    ]);

    return <input className={ffClasses} {...props} />;
};

// packages/adapters/svelte/src/Input.svelte
<script lang="ts" context="module">
  export const __ffClasses_Input = [
    'ff-input',
    'ff-input-error'
  ];
</script>

<script lang="ts">
  import { useFinggu } from './context';

  export let error: boolean = false;

  const finggu = useFinggu();

  $: ffClasses = $finggu.resolveAll([
    'ff-input',
    error && 'ff-input-error',
    $$props.class
  ]);
</script>

<input class={ffClasses} {...$$restProps} />
