// packages/adapters/react/src/modal.tsx
import React, { useEffect, useState } from 'react';
import { useFinggu } from './provider';

export interface ModalProps {
    isOpen: boolean;
    onClose: () => void;
    children: React.ReactNode;
    className?: string;
}

export const __ffClasses_Modal = [
    'ff-modal',
    'ff-modal-open',
    'ff-modal-closed',
    'ff-modal-overlay',
    'ff-modal-content'
];

export const Modal: React.FC<ModalProps> = ({ isOpen, onClose, children, className }) => {
    const { resolveAll } = useFinggu();
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        if (isOpen) {
            setMounted(true);
            document.body.style.overflow = 'hidden';
        } else {
            const timer = setTimeout(() => setMounted(false), 300); // Wait for exit animation
            document.body.style.overflow = '';
            return () => clearTimeout(timer);
        }
    }, [isOpen]);

    if (!mounted && !isOpen) return null;

    return (
        <div
            className={resolveAll(['ff-modal', isOpen ? 'ff-modal-open' : 'ff-modal-closed'])}
            aria-hidden={!isOpen}
        >
            <div className="ff-modal-overlay" onClick={onClose} />
            <div className={resolveAll(['ff-modal-content', className])}>
                {children}
            </div>
        </div>
    );
};

// packages/adapters/svelte/src/Modal.svelte
<script lang="ts" context="module">
  export const __ffClasses_Modal = [
    'ff-modal',
    'ff-modal-open',
    'ff-modal-closed',
    'ff-modal-overlay',
    'ff-modal-content'
  ];
</script>

<script lang="ts">
  import { onMount, createEventDispatcher } from 'svelte';
  import { useFinggu } from './context';

  export let isOpen: boolean = false;

  const dispatch = createEventDispatcher();
  const finggu = useFinggu();
  
  let mounted = false;
  let animating = false;

  onMount(() => {
    mounted = true;
  });

  $: if (isOpen) {
    if (typeof document !== 'undefined') {
      document.body.style.overflow = 'hidden';
      animating = true;
    }
  } else {
    if (typeof document !== 'undefined') {
      setTimeout(() => {
        animating = false;
        document.body.style.overflow = '';
      }, 300); // Exit animation duration
    }
  }

  $: ffContainerClasses = $finggu.resolveAll([
    'ff-modal',
    isOpen ? 'ff-modal-open' : 'ff-modal-closed'
  ]);

  $: ffContentClasses = $finggu.resolveAll([
    'ff-modal-content',
    $$props.class
  ]);
</script>

{#if mounted && (isOpen || animating)}
  <div class={ffContainerClasses} aria-hidden={!isOpen}>
    <div class="ff-modal-overlay" on:click={() => dispatch('close')} />
    <div class={ffContentClasses}>
      <slot />
    </div>
  </div>
{/if}
